#!/usr/bin/env bash

set -euo pipefail
SCRIPT_DIR="$(dirname ${BASH_SOURCE})/scripts"
source "$SCRIPT_DIR/lib.sh"

readonly IS_RUNNING="$(docker container inspect -f '{{.State.Running}}' $CONTAINER_NAME 2> /dev/null)"
if [ "$IS_RUNNING" != "true" ]; then
  $SCRIPT_DIR/start.sh
fi

# Even though the container has started, ssh might not be ready yet.
# So we wait until we're sure its ready.
until [ "$(ssh -i keys/$USER_SSH_KEY_NAME -p 2222  "$CONTAINER_USER@localhost" echo 'running')" == "running" ]
do
    sleep 1
done

ssh -A -i keys/$USER_SSH_KEY_NAME -p 2222 "$CONTAINER_USER@localhost"
