#!/usr/bin/env bash

set -euo pipefail
source "$(dirname ${BASH_SOURCE})/lib.sh"
source "$(dirname ${BASH_SOURCE})/version.sh"
HOME_DIR="/home/$CONTAINER_USER"

docker run -it --rm \
    -h kdevenv \
    --name liveenv \
    --env SHELL="$CONTAINER_SHELL" \
    --volume "$HOME_VOLUME:$HOME_DIR" \
    --volume "/var/run/docker.sock:/var/run/docker.sock" \
    --workdir "$HOME_DIR" \
    --user "$CONTAINER_USER" \
    -p 8080:8080 \
    "kdevenv:${KDEVENV_VERSION}" \
    $CONTAINER_SHELL
